### ISSUE TITLE
No connection with (self-signed) SSL configured

### ISSUE THREAD

**Issue by jo-me** [lukas-hetzenecker/home-assistant-remote#11]
Hi,
I'm trying out your component on Hassio 0.98.4 in combination with a fresh remote HA instance with the same version.

When the remote instance has no ssl configured a connection seems to be established (at least no error in the log and the websocket connection counter increases on the remote instance.

Config in remote HA is like this:
```
http:

websocket_api:
```

Config in master HA instance is like this:
```
remote_homeassistant:
  instances:
  - host: <hostname>
    port: 8124
    secure: false
    access_token: !secret hazwave_token
    entity_prefix: "hazwave_"
    subscribe_events:
    - state_changed
    - service_registered
    - zwave.network_ready
    - zwave.node_event
```

However, when I enable SSL on the remote instance and set "secure: true" on the master instance I only get repeated connection errors without further hints.

The config of the remote instance is like this:
```
http:
  ssl_certificate: ssl/hassio.pem
  ssl_key: ssl/hassio.key

websocket_api:
```

The HA web interface works as expected. Due to the imported root cert, the connection is trusted and green in Chrome.

Could it be that there is an issue when self-signed certificates are used? 
Is there an option to ignore ssl warnings?

Thanks!
