### ISSUE TITLE
host using https setup?

### ISSUE THREAD

**Issue by vMeph** [lukas-hetzenecker/home-assistant-remote#17]
for some reason having a hard time to se connection when using https:,i have tried almost everything and the erro is always same, when i tried local was no problem

```
remote_homeassistant:
  instances:
  - host: https://xxxxxxxxxxxx.duckdns.org:8123
    port: 8123
    secure: false
    verify_ssl: false
    access_token: !secret test
    entity_prefix: "slave_"
    subscribe_events:
     - state_changed
     - service_registered
```
dont matter what i do the erro is always same
`Could not connect to ws://xxxxxxxxxxxxxxxxxxxx.duckdns.org:8123:8123/api/websocket,`
