### ISSUE TITLE
Error when starting homekit

### ISSUE THREAD

**Issue by mattlongman** [lukas-hetzenecker/home-assistant-remote#23]
Firstly, this component seems like a true miracle after messing around with socat, ser2net and usbip for what seems like forever, so, thank you!

I'm having an issue with with it when I start the homekit component. I have homekit disabled on startup, but when I run homekit.start, I immediately see the following in the log:

`019-10-30 18:36:54 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 264, in _recv
    callback(message)
  File "/config/custom_components/remote_homeassistant/__init__.py", line 387, in fire_event
    self._entities.remove(entity_id)
KeyError: 'persistent_notification.config_entry_discovery'`

After that, I might be able to switch one or two devices on or off (status might update in master hassio or homekit, mainly doesn't) before the devices on the remote instance stop being controllable from the master (locally and through homekit control).

I'm using the current version. I've tried changing the default port, but get the same result. Also tried removing all subscribe events, same result.

I'm seeing this behaviour in homeassistant version 0.100.3 & 0.101.0.

My config:

```
remote_homeassistant:
  instances:
  - host: !secret usb_ip
    port: 8234
    access_token: !secret usb
    entity_prefix: "usb_"
    include:
      domains:
      - sensor
      - switch
      - group
      - light
      - climate
    subscribe_events:
    - state_changed
    - service_registered
    - zwave.network_ready
    - zwave.node_event
```
Is there anything I'm missing?
