### ISSUE TITLE
Could not connect to websocket

### ISSUE THREAD

**Issue by fxxer** [lukas-hetzenecker/home-assistant-remote#55]
I generated the long term token and successfuly tried it manualy to get sensor data. But I am getting error when I setup this component. Am I missing something, please help.

`2020-10-20 10:54:14 ERROR (MainThread) [custom_components.remote_homeassistant] Could not connect to ws://192.168.X.XX:8123/api/websocket, retry in 10 seconds...`

my config:
```
remote_homeassistant:
  instances:
    - host: 192.168.X.XX
      port: 8123
      access_token: "token"

```
