### ISSUE TITLE
Support for tempalte in host config?

### ISSUE THREAD

**Issue by krasatos** [lukas-hetzenecker/home-assistant-remote#6]
For some reason, the DuckDNS add-on on a remote hassio keeps turning off so, I’m trying to set up a backup system for my ‘remote_homeassistant’ component.
I set up an automation on the remote home assistant to email me its ip every x hours, and i have created an SMTP sensor to read the ip.
So now i have a sensor.remote_ip which is (almost) always up to date.
Unfortunatelly, i guess the component does not support templating so my following config does not work.
```
remote_homeassistant:
  instances:
  - host: {{states.sensor.ha_remote_ip.state}}
    port: !secret ha_remote_port
    secure: true
    access_token: !secret ha_remote_access_token
    entity_prefix: !secret ha_remote_entity_prefix
```
Is there any way to work around this?
