### ISSUE TITLE
Sensor Data do not get updated

### ISSUE THREAD

**Issue by herrlado** [lukas-hetzenecker/home-assistant-remote#60]
remote connected

![Screenshot from 2020-11-12 20-00-09](https://user-images.githubusercontent.com/192286/98983857-b245cf00-2521-11eb-8b15-c5a9cc334323.png)

The sensor state is from that time (connected and ago time are the same)
![Screenshot from 2020-11-12 20-00-42](https://user-images.githubusercontent.com/192286/98983987-dc978c80-2521-11eb-9c5f-62a7f296fdfa.png)

After that nothing happens. On the remote machine the sensors get updated
![Screenshot from 2020-11-12 20-02-06](https://user-images.githubusercontent.com/192286/98984054-f5a03d80-2521-11eb-975b-50faa4ed83c2.png)

Here is my config

```yaml
remote_homeassistant:
  instances:
  - host: 192.168.1.78
    port: 8123
    access_token: !secret slave_token
    entity_prefix: slave_
    include:
      domains:
      - sensor
```
